#!/bin/sh
# SPDX-FileCopyrightText: Copyright (C) 2026, UAB Kurokesu
# SPDX-License-Identifier: GPL-3.0-or-later
#
# initramfs hook: bundle the kernel fullscreen-logo TGA so fbcon can draw it
# at boot. Same mechanism as rpi-splash-screen-support's default hook.
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

add_firmware logo.tga
